github.com:
    users:
        pintoduoc:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: pintoduoc
