[Setting]
spotify_path           = /home/pinto/.local/share/spotify-launcher/install/usr/share/spotify
prefs_path             = /home/pinto/.config/spotify/prefs
current_theme          = Sleek
color_scheme           = Nord
inject_css             = 1
overwrite_assets       = 1
spotify_launch_flags   = --enable-features=UseOzonePlatform --ozone-platform=wayland
always_enable_devtools = 0
inject_theme_js        = 1
replace_colors         = 1
check_spicetify_update = 1

[Preprocesses]
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1

[AdditionalOptions]
sidebar_config        = 0
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = marketplace

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.96.518.g366879e1
with    = 2.45.0
